### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by EmptyChan** [VegetableCat/javID-SearchTool#1]
hi，兄弟，你的东西我看了源码，跑了一个番号。在创建文件夹时太长的日文名会导致文件夹创建失败，我clone下来自己改成了uuid1。哈哈。

**Comment by VegetableCat** [comment]
哈哈 可以的～
我还没有遇到名字太长的情况，可否说下车牌号呢～谢谢

2017-01-22 18:44 GMT+08:00 EmptyChan <notifications@github.com>:

**Comment by EmptyChan** [comment]
我在首页找了两个ONGP-078和SGA-076，你试试吧，哈哈，我觉得这种可以改成uuid1。ヽ(。_°)ノ

**Comment by VegetableCat** [comment]
但是用uuid1的话 就不知道下载的车牌是啥了 
我截取了一下名字的长度 （反正日文我也看不懂
应该不会出错了O(∩_∩)O~~
thanks a lot
